"""Per-faction mana pool (regenerated by buildings).

Per asm/CONSTRUCTION_REPORT.md: mana accumulates while buildings grow. v1
implementation: each non-destroyed house regenerates a small amount per
second for its faction, capped at a soft maximum.
"""

import populous_game.settings as settings


class ManaPool:
	"""Manages mana per faction."""

	def __init__(self, factions: list):
		self._mana: dict = {fid: settings.INITIAL_MANA for fid in factions}

	def get_mana(self, faction_id: int) -> float:
		"""Get current mana for a faction."""
		return self._mana.get(faction_id, 0.0)

	def add(self, faction_id: int, amount: float) -> None:
		"""Add mana to a faction (capped at soft maximum)."""
		self._mana[faction_id] = min(
			settings.PEEP_LIFE_MAX * 4,  # generous soft cap
			self._mana.get(faction_id, 0.0) + amount,
		)

	def spend(self, faction_id: int, amount: float) -> bool:
		"""Spend mana from a faction. Return False if insufficient."""
		if self._mana.get(faction_id, 0.0) < amount:
			return False
		self._mana[faction_id] -= amount
		return True

	def regen_from_houses(self, houses: list, dt: float) -> None:
		"""Regenerate mana from non-destroyed houses."""
		for h in houses:
			if h.destroyed:
				continue
			self.add(h.faction_id,
				settings.MANA_REGEN_PER_HOUSE_PER_SEC * dt)
